apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - argocd/ingress.yaml
  - postgres/postgres.yaml
  - postgres/pgadmin.yaml
  - kafka/kafka-nodepool.yaml
  - kafka/kafka-cluster.yaml
  - kafka/topics.yaml
  - kafka/kafka-ui.yaml
  - app/backend
  - app/frontend
  - app/consumer