apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app/ingress-nginx.yaml
  - app/strimzi-operator.yaml
  - namespace/postgres.yaml

configMapGenerator:
- name: postgres-config
  literals:
    - "POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
  namespace: postgres

secretGenerator:
- name: postgres-credentials
  literals:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=messages
  namespace: postgres

generatorOptions:
  disableNameSuffixHash: true